### ISSUE TITLE
Enhacements

### ISSUE THREAD

**Issue by Maximus7474** [YeeetSK/Yetti-EvidenceBoxes#2]
I challenge you to make it better 🤣 
Here are a couple ideas to improve it:

- [x] have a certain stash have a custom model and if not defined goes to the default one
- [x] have optionnal size config for each stash
- [x] #3
  - Well it is an evidence script but hey you can have FIB, LSPD, BCSO, LSSD each can have there own private evidence or a global police one.

**Comment by YeeetSK** [comment]
Will upload new version soon
